[package]
name = "synth-gen"
version = "0.4.1"
authors = [
  "Damien Broka <damien@getsynth.com>",
  "Christos Hadjiaslanis <christos@getsynth.com>"
]
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
serde_json = "1.0"

[features]
default = [ ]
faker = [ "fake" ]
shared = [ ]

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
ordered-float = { version = "5.1.0", features = ["serde", "rand"] }
fake = { version = "4.4.0", features = ["http"], optional = true }
rand = "0.9.2"
